version: '3.8'

services:
  DIAMOND_POSTGRES:
    image: postgres:15
    container_name: DIAMOND_DATABASE
    restart: always
    environment:
      POSTGRES_USER: diamond 
      POSTGRES_PASSWORD: dev 
      POSTGRES_DB: DIAMOND 
    ports:
      - "5451:5432"
    volumes:
      - ./Volumes:/var/lib/postgresql/data

volumes:
  pgdata: